In [1]:
import numpy as np

In [3]:
# Array creation
arr = np.array([1, 2, 3])

In [4]:
arr

array([1, 2, 3])

In [22]:
# MulitD array
arr2 = np.array(
    [
        [
            [1,2,3],
            [2,3,4]
        ],
        [
            [1,2,3],
            [2,3,4]
        ]
    ]
)

In [23]:
arr2

array([[[1, 2, 3],
        [2, 3, 4]],

       [[1, 2, 3],
        [2, 3, 4]]])

In [24]:
arr2.ndim

3

In [25]:
arr2.shape

(2, 2, 3)

In [27]:
type(arr2)

numpy.ndarray

In [31]:
# Type of the array can be specified at creation time
c = np.array([1,2,3], dtype=complex)
c

array([1.+0.j, 2.+0.j, 3.+0.j])

In [54]:
#zeores, ones and empty. default type is float
a_zeros = np.zeros((2,3), dtype=int)
a_ones = np.ones((2,3,4))
a_empty = np.empty(4)
a_empty

array([ 0.00000000e+000, -3.10503637e+231,  2.47032823e-323,
        0.00000000e+000])

In [59]:
# Sequence of numbers
a = np.arange(1,5,3) # from, to, gap
a
a_line_space = np.linspace(0,2,9) # from, to, no. of 
a_line_space

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [62]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [76]:
# Basic operations
# Arthematic operations are done row wise
# Creates a new array on every operation
a = np.arange(1,10,1)
b = np.arange(1,10,2)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
a%2==0

array([False,  True, False,  True, False,  True, False,  True, False])

In [72]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
a*a

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [77]:
a*b

ValueError: operands could not be broadcast together with shapes (9,) (5,) 

In [80]:
# Some operations such as += and *= operate in place and doesnt create a new array
a = np.array([1,2,3])
b = np.array([2,3,4])
a *= 2

In [81]:
a

array([2, 4, 6])

In [82]:
b += a

In [83]:
b

array([ 4,  7, 10])

In [89]:
a = np.array([1.0, 0, 12])

In [91]:
# Unary operators
a = np.array([[1,2,3],[2,4,5]])

In [92]:
a

array([[1, 2, 3],
       [2, 4, 5]])

In [93]:
a.sum()

17

In [94]:
a.min()

1

In [95]:
a.max()

5

In [100]:
a = np.ones((2,3,4), dtype=int)

In [101]:
a.sum(axis=0) # it will snap that axes, aggregates over it and will be remained with remaining axes

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [102]:
a.sum(axis=1)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [104]:
# slicing
a = np.array([1,2,3,4,5,6])
a[2::2]# step

array([3, 5])

In [105]:
a[::-1]# -1 represents reverse

array([6, 5, 4, 3, 2, 1])

In [109]:
#from function
def fn(x,y):
    return x*y
b = np.fromfunction(fn, (5,5), dtype=int)
b

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

In [111]:
b[2,3]

6

In [113]:
b[2:4,1:3]

array([[2, 4],
       [3, 6]])

In [115]:
b[2]

array([0, 2, 4, 6, 8])

In [116]:
#
# The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then
#
# x[1,2,...] is equivalent to x[1,2,:,:,:],
# x[...,3] to x[:,:,:,:,3] and
# x[4,...,5,:] to x[4,:,:,5,:]
# */

SyntaxError: invalid syntax (<ipython-input-116-db327a9eee14>, line 2)

In [128]:
#flat attribute: iterates over every element
b = np.zeros((2,2), dtype=int)

In [129]:
for i in b.flat:
    print(i)

0
0
0
0


In [130]:
#Shaping an array

In [134]:
b = np.zeros((2,2))

In [135]:
b

array([[0., 0.],
       [0., 0.]])

In [146]:
b.ravel() # returns flattened

array([0., 0., 0., 0.])

In [147]:
b.reshape((4))

array([0., 0., 0., 0.])

In [149]:
b.T # traspose

array([[0., 0.],
       [0., 0.]])

In [150]:
# if a dimension is given as -1, then it would be automatically calculated

In [ ]:
#stacking and splitting

In [158]:
a = np.zeros((2,2))
b = np.ones((2,2))
np.hstack((a,b))

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [161]:
np.vstack((b,a,a,b))

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [162]:
#column stack

In [163]:
#row stack

In [164]:
#splitting

In [165]:
#shallow copy

In [170]:
b = np.zeros(4)
a = b
b is a

True

In [171]:
#deep copy

In [172]:
b = np.zeros(4)
a = b.copy()
b is a

False

In [173]:
#views or shallow copy

In [175]:
b = np.zeros(4)
a = b.view()
a is b

False

In [179]:
a.base is b

True

In [180]:
a.shape = 4

In [188]:
a

array([0., 0., 0., 0.])

In [189]:
b

array([0., 0., 0., 0.])

In [185]:
b.flags.owndata

True

In [186]:
a.flags.owndata

False

In [192]:
str = '''
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

Array Creation
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r, zeros, zeros_like
Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat
Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack
Questions
all, any, nonzero, where
Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort
Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum
Basic Statistics
cov, mean, std, var
Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot
Ref : 
https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html#functions-and-methods-overview
'''